# Generated by Django 5.1.4 on 2025-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_tournament_game',
            field=models.BooleanField(default=False),
        ),
    ]
