<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-03-17 14:26
=======
# Generated by Django 5.1.4 on 2025-03-17 11:48
>>>>>>> a7f85ea65d7a6003d8e8447faf703da122afc30e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_tournament_game',
            field=models.BooleanField(default=False),
        ),
    ]
