# Generated by Django 5.1.4 on 2025-02-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameconfig',
            name='server_url',
        ),
    ]
