# Generated by Django 5.1.4 on 2025-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameconfig_server_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='side',
            field=models.IntegerField(default=0),
        ),
    ]
