# Generated by Django 5.1.4 on 2025-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playerstate_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='player_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstate',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstate',
            name='side',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
