# Generated by Django 5.1.4 on 2025-02-20 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerstate_player_number_playerstate_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(related_name='game_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
