# Generated by Django 5.1.4 on 2025-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameroom_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
