# Generated by Django 5.1.4 on 2025-02-26 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playerstate_is_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], default='OPEN', max_length=20)),
                ('max_players', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('active_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_lobby', to='game.gameroom')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lobbies',
            },
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_players', to='game.lobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lobby', 'player')},
            },
        ),
    ]
