# Generated by Django 5.1.4 on 2025-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_lobby_lobbyplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
