# Generated by Django 5.1.4 on 2025-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_lobby_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], default='OPEN', max_length=20),
        ),
    ]
