# Generated by Django 5.1.4 on 2025-03-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_lobby_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='lobby',
        ),
        migrations.AlterUniqueTogether(
            name='lobbyplayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='player',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='LobbyPlayer',
        ),
    ]
