# Generated by Django 5.1.4 on 2025-02-22 11:31

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=apps.users.models.user_profile_path),
        ),
    ]
