# Generated by Django 5.1.4 on 2025-03-19 14:07

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', upload_to=apps.users.models.user_profile_path),
        ),
    ]
