services:
  redis:
    image: redis:latest

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src:/app/src
      - django_media:/app/src/apps/users/media
    ports:
      - "8000:8000"
    command: ["./src/entrypoint-prod.sh"]
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src/
          target: app/src/

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
  django_media:
