services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - default

    restart: unless-stopped


  db:
    container_name: database
    image: postgres:13
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

    restart: unless-stopped


  web:
    container_name: web
    build:
      dockerfile: src/Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - default
    volumes:
      - source:/app/src
      - media:/app/media
      - static:/app/static

    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.dev
    env_file:
      - .env

    develop:
      watch:
        - action: sync
          path: ./src/
          target: app/src/

    restart: unless-stopped



volumes:
  postgres_data:

  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./media

  source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/

  static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static/



networks:
  default:
    name: transcendence
    driver: bridge
