services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src:/app/src
      # - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src/
          target: app/src/

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_data:
