# Generated by Django 5.1.4 on 2025-05-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='player_count',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_winner', to='game.tournamentplayer'),
        ),
    ]
