# Generated by Django 5.1.4 on 2025-04-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettings',
            name='mode',
        ),
    ]
