# Generated by Django 5.1.4 on 2025-04-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
    ]
