# Generated by Django 5.1.4 on 2025-04-23 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gamesettings_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game_settings',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='bracket',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_type',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='has_withdrawn',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='map',
            field=models.CharField(choices=[('classic', 'Classic'), ('bath', 'Bath'), ('lava', 'Lava'), ('beach', 'Beach')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player_count',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='map',
            field=models.CharField(choices=[('classic', 'Classic'), ('bath', 'Bath'), ('lava', 'Lava'), ('beach', 'Beach')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_count',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.DeleteModel(
            name='GameSettings',
        ),
    ]
