# Generated by Django 5.1.4 on 2025-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_tournament_game_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={},
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='is_connected',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='is_ready',
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
