# Generated by Django 5.1.4 on 2025-04-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress')], default='waiting', max_length=20),
        ),
    ]
