# Generated by Django 5.1.4 on 2025-01-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
